// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLdDireWKZFFvaOXIK57fBVzyJhuk2XzM',
    appId: '1:82695125161:web:bbafb70ee6d46c717351b8',
    messagingSenderId: '82695125161',
    projectId: 'fortlinedatabase-bfdb9',
    authDomain: 'fortlinedatabase-bfdb9.firebaseapp.com',
    storageBucket: 'fortlinedatabase-bfdb9.appspot.com',
    measurementId: 'G-ELSH0XCM7Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbZfg0yYtgCjTLXKkL7mx7cRfDhdOiirI',
    appId: '1:82695125161:android:58430f84bcb323687351b8',
    messagingSenderId: '82695125161',
    projectId: 'fortlinedatabase-bfdb9',
    storageBucket: 'fortlinedatabase-bfdb9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-lmn3d_cr3PcHYVj5jTOGmZtp9vT5zzA',
    appId: '1:82695125161:ios:7a54a67469135d447351b8',
    messagingSenderId: '82695125161',
    projectId: 'fortlinedatabase-bfdb9',
    storageBucket: 'fortlinedatabase-bfdb9.appspot.com',
    iosClientId: '82695125161-nj3r3qbj06gg2upb2fg5584f8a70f43g.apps.googleusercontent.com',
    iosBundleId: 'com.sc.fortlineAdminApp',
  );
}
